# Generated by Django 3.2.6 on 2021-09-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210915_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='count',
        ),
    ]
